[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "postgresql"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public/ router.php"