[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "postgresql"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
    "echo 'Running database migrations during build...'",
    "php bin/deploy-hook.php migrate-seed"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public/ router.php"