[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "postgresql"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
    "echo 'Build completed. Migrations will run at startup.'"
]

[start]
cmd = "php bin/start-simple.php"