services:
  php:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspace:cached
    working_dir: /workspace
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=portfolio_db
      - DB_USER=portfolio_user
      - DB_PASSWORD=portfolio_password

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: portfolio_password
    ports:
      - "5432:5432"

volumes:
  postgres-data: